server:
  port: 8080
  tomcat:
    threads:
      max: 1000
      min-spare: 30
    uri-encoding: UTF-8
  max-http-request-header-size: 32KB

spring:
  application:
    name: SQLBrigerAI
  profiles:
#    active: dev
    active: default
#    active: @profiles.activate@
  main:
    banner-mode: off
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
  threads:
    virtual:
      enabled: false

langchain4j:
  open-ai:
    chat-model:
      base-url: http://langchain4j.dev/demo/openai/v1
      api-key: demo
      model-name: gpt-4o-mini
      timeout: 30000
      max-tokens: 2000
    streaming-chat-model:
      api-key: demo
    moderation-model:
      base-url: http://langchain4j.dev/demo/openai/v1
      api-key: demo
      model-name: text-moderation-latest
      timeout: 30000
  chat-store: DB # MEMORY or DB
  store-expires: 1

logging:
  level:
    root: WARN
    orgapache: WARN
    org.springframework: INFO
    com.xml: DEBUG
  pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{traceId}][%thread] %-5level %logger [%line] - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{traceId}][%thread] %-5level %logger [%line] - %msg%n"
  file:
    name: ./logs/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
